blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
color = "Always"
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 5
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = true
hex_literal_case = "Lower"
imports_granularity = "Module"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
indent_style = "Block"
overflow_delimited_expr = true
struct_field_align_threshold = 5
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true